// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: serverstreaming.proto

package ServerStreaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerStreamingClient is the client API for ServerStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerStreamingClient interface {
	// A server streaming RPC.
	ProcessIO(ctx context.Context, in *Number, opts ...grpc.CallOption) (ServerStreaming_ProcessIOClient, error)
}

type serverStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStreamingClient(cc grpc.ClientConnInterface) ServerStreamingClient {
	return &serverStreamingClient{cc}
}

func (c *serverStreamingClient) ProcessIO(ctx context.Context, in *Number, opts ...grpc.CallOption) (ServerStreaming_ProcessIOClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerStreaming_ServiceDesc.Streams[0], "/ServerStreaming.ServerStreaming/ProcessIO", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverStreamingProcessIOClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerStreaming_ProcessIOClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type serverStreamingProcessIOClient struct {
	grpc.ClientStream
}

func (x *serverStreamingProcessIOClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServerStreamingServer is the server API for ServerStreaming service.
// All implementations must embed UnimplementedServerStreamingServer
// for forward compatibility
type ServerStreamingServer interface {
	// A server streaming RPC.
	ProcessIO(*Number, ServerStreaming_ProcessIOServer) error
	mustEmbedUnimplementedServerStreamingServer()
}

// UnimplementedServerStreamingServer must be embedded to have forward compatible implementations.
type UnimplementedServerStreamingServer struct {
}

func (UnimplementedServerStreamingServer) ProcessIO(*Number, ServerStreaming_ProcessIOServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessIO not implemented")
}
func (UnimplementedServerStreamingServer) mustEmbedUnimplementedServerStreamingServer() {}

// UnsafeServerStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerStreamingServer will
// result in compilation errors.
type UnsafeServerStreamingServer interface {
	mustEmbedUnimplementedServerStreamingServer()
}

func RegisterServerStreamingServer(s grpc.ServiceRegistrar, srv ServerStreamingServer) {
	s.RegisterService(&ServerStreaming_ServiceDesc, srv)
}

func _ServerStreaming_ProcessIO_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Number)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerStreamingServer).ProcessIO(m, &serverStreamingProcessIOServer{stream})
}

type ServerStreaming_ProcessIOServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type serverStreamingProcessIOServer struct {
	grpc.ServerStream
}

func (x *serverStreamingProcessIOServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

// ServerStreaming_ServiceDesc is the grpc.ServiceDesc for ServerStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServerStreaming.ServerStreaming",
	HandlerType: (*ServerStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessIO",
			Handler:       _ServerStreaming_ProcessIO_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "serverstreaming.proto",
}
